version: '3.7'

services:
    db: 
      image: postgres
      restart: always
      environment: 
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: homestead
        PGDATA: /var/lib/postgresql/data
      volumes: 
        - pgdata:/var/lib/postgresql/data
      ports:
        - 5432:5432

    adminer:
        image: adminer
        depends_on: 
            - db
        restart: always
        ports:
            - 8090:8080
volumes: 
    pgdata: